---
version: '3'
services:
  api:
    build:
      context: ./api
    container_name: api
    volumes:
      - ./api:/app:delegated
    ports:
      - '5000:5000'
    #env_file: ./api/.env

  inference:
    image: rasa/rasa:1.10.8-full
    ports:
      - '5005:5005'
    depends_on:
      - action_server
    volumes:
      - ./inference:/app:delegated
    command:
      - run

  action_server:
      image: rasa/rasa-sdk:2.0.0a1
      volumes:
        - ./actions:/app/actions:delegated
  redis:
    image: redis:6.0.6
