---
version: '3'
services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
     - .env
  api_server:
    build:
      context: ./api
    container_name: api_server
    volumes:
      - ./api:/app:delegated
    ports:
      - '5000:5000'
    depends_on:
      - inference_server
      - db
    env_file:
       - .env

  inference_server:
    image: rasa/rasa:1.10.8-full
    container_name: inference_server
    depends_on:
      - action_server
    volumes:
      - ./inference:/app:delegated
    command:
      - run

  action_server:
      container_name: action_server
      image: rasa/rasa-sdk:2.0.0a1
      volumes:
        - ./actions:/app/actions:delegated
  redis:
    image: redis:6.0.6

volumes:
  postgres_data:
